### ISSUE TITLE
Dropbox URL with datasets is not accessible

### ISSUE THREAD

**Issue by pablojrios** [ToniCreswell/pyTorch_DAAE#2]
Informed URL to download data from https://www.dropbox.com/sh/8oqt9vytwxb3s4r/AAB06FXaQRUNtjW9ntaoPGvCa?dl=0 is not accessible.

**Comment by pablojrios** [comment]
CelebA dataset can be downloaded from Google or Baidu drives referenced from http://mmlab.ie.cuhk.edu.hk/projects/CelebA.html.

**Comment by ToniCreswell** [comment]
Hi, thanks for finding this error and for sharing this new link. I very much appreciate this, thank you.
